#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/tmp/$USER/ovltar_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
test -n "$1" || die "No out-file"
sh=$dir/../../sdl.sh
test -x $sh || die "Not executable [$sh]"
eval $($sh env)
eval $($sh versions --brief)
sysd=$__sysd/usr/local
mkdir -p $tmp/bin $tmp/usr/lib $tmp/lib

# Legacy support for directfb and drminfo
if test -x $sysd/lib/libdirectfb-1.7.so.7; then
	mkdir -p $tmp/lib64
	$sh libs || die
	cp $sysd/lib/libdirectfb-1.7.so.7 $tmp/lib64
	cp $(LD_LIBRARY_PATH=$sysd/lib $sh libs $sysd/lib/libdirectfb-1.7.so.7) \
		$tmp/lib64
	d=/tmp/tmp/uablrek/SDL/sys/usr/local/lib/directfb-1.7-7-pure/systems
	if test -d $d; then
		mkdir -p $tmp/usr/local/lib/directfb-1.7-7-pure
		cp -r $d $tmp/usr/local/lib/directfb-1.7-7-pure
	fi
fi
if test -x $sysd/bin/drminfo; then
	mkdir -p $tmp/lib64
	$sh libs || die
	cp $sysd/bin/drminfo $sysd/bin/fbinfo $tmp/bin
	cp $($sh libs $sysd/bin/drminfo $sysd/bin/fbinfo) $tmp/lib64
fi

test -r $sysd/lib/libSDL2-2.0.so.0 || die "SDL2 not built"
cp -L $sysd/lib/lib*.so.[0-9] $tmp/lib

d=$sysd/libexec/installed-tests/SDL2
test -x $d/testdraw2 && cp $d/* $tmp/bin
cp $sysd/bin/* $tmp/bin


# Dri support is at different places for native and musl
if test -d $sysd/lib/x86_64-linux-gnu/dri; then
	mkdir -p $tmp/usr/local/lib/x86_64-linux-gnu/dri
	for f in swrast_dri.so kms_swrast_dri.so virtio_gpu_dri.so; do
		cp $sysd/lib/x86_64-linux-gnu/dri/$f \
			$tmp/usr/local/lib/x86_64-linux-gnu/dri
	done
elif test -d $sysd/lib/dri; then
	mkdir -p $tmp/usr/local/lib/dri
	for f in swrast_dri.so kms_swrast_dri.so virtio_gpu_dri.so v3d_dri.so; do
		cp $sysd/lib/dri/$f $tmp/usr/local/lib/dri
	done
	#cp $sysd/lib/dri/* $tmp/usr/local/lib/dri
fi

if test "$__musl" != "yes"; then
	mkdir -p $tmp/lib
	cp -L /usr/lib/x86_64-linux-gnu/libzstd.so.1 \
		/usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
		/usr/lib/x86_64-linux-gnu/libgcc_s.so.1 \
		/usr/lib/x86_64-linux-gnu/libcap.so.2 \
		/usr/lib/x86_64-linux-gnu/libz.so.1 \
		/usr/lib/x86_64-linux-gnu/libc.so.6 \
		/usr/lib/x86_64-linux-gnu/libm.so.6 \
		$tmp/lib
	# Overwrite Ubuntu libs with local ones
	test -d $sysd/lib/x86_64-linux-gnu && \
		cp -L $sysd/lib/x86_64-linux-gnu/*.so.[0-9] $tmp/lib
	# Fallback if libudev is not built
	test -r $tmp/lib64/libudev.so.1 || \
		cp /usr/lib/x86_64-linux-gnu/libudev.so.1 $tmp/lib
fi

$sh strip $tmp

cp -r $dir/* $tmp
cd $tmp
tar --exclude='tar' --exclude='README.md' -cf "$1" *
cd $dir
rm -rf $tmp
