#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/tmp/$USER/ovltar_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
test -n "$1" || die "No out-file"
sh=$dir/../../sdl.sh
test -x $sh || die "Not executable [$sh]"
eval $($sh env)
eval $($sh versions --brief)
mkdir -p $tmp

d=$SDL_WORKSPACE/$__arch/$ver_scummvm/sys
test -d $d/usr || die "Not a dir [$d/usr]"
cp -R $d/usr $tmp

cd $tmp
tar -cf "$1" *
cd $dir
rm -rf $tmp
