#! /bin/sh
/bin/busybox echo "=== Linux SDL starting..."
/bin/busybox mkdir -p /proc /sys /tmp /dev/pts /dev/shm /var/log \
	/sbin /usr/bin /usr/sbin
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox --install -s
mdev -s

mkdir -p /run /var/log/dumps /var/tmp
ln -s /run /var/run

mount /tmp

#echo /sbin/mdev > /proc/sys/kernel/hotplug

mount /dev/shm
mount /dev/pts
mount -o remount -w /
mdev -s

sysctl -p > /dev/null
exec /sbin/init
