#! /bin/sh
# NOTE: A common pattern is to specify "-" (stdout) as out-file,
#  so there must be NO log printouts to stdout!

dir=$(dirname $0); dir=$(readlink -f $dir)
tmp=/tmp/tmp/$USER/ovltar_$$
die() {
	echo "ERROR: $*" >&2
	rm -rf $tmp
	exit 1
}
log() {
	echo "INFO: $*" >&2
}
test -n "$1" || die "No out-file"
mkdir -p $tmp
cp $dir/init $tmp

cd $tmp
tar --exclude='tar' --exclude='README.md' -cf "$1" *
cd $dir
rm -rf $tmp
